# Generated by Django 5.2.5 on 2025-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp1', '0002_m_model_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('course', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
