# Generated by Django 5.2.5 on 2025-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp1', '0005_student_details_delete_emp_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='phone',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
