# Generated by Django 5.2.5 on 2025-08-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp1', '0007_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dapp1.author'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_price',
            field=models.IntegerField(),
        ),
    ]
